GEN_MODEL = "tiiuae/Falcon3-1B-Instruct"
MAX_NEW_TOKENS = 256
MIN_NEW_TOKENS = 8
NUM_BEAMS = 3
EARLY_STOPPING = True

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
TOP_K = 5

BASIC_CORPUS = [
    "The four fundamental forces of flight are lift, weight, thrust, and drag. Lift is generated by the wings, weight is the force of gravity acting on the aircraft.",
    "The primary flight controls consist of the elevator for pitch control, rudder for yaw control, and ailerons for roll control.",
    "Aircraft engines can be classified as reciprocating engines, turboprops, turbojets, or turbofans, each with different operating principles.",
    "The Federal Aviation Administration (FAA) regulates aviation safety through certification requirements, operating procedures, and maintenance standards.",
    "Airspace is divided into controlled and uncontrolled areas, with Class A, B, C, D, E, and G airspace having different operational requirements.",
    "Weather conditions significantly affect flight safety, including visibility, wind, turbulence, icing, and thunderstorms.",
    "Navigation systems include GPS, VOR, ADF, and ILS, providing pilots with accurate position and approach guidance.",
    "Aircraft performance is affected by factors such as weight, altitude, temperature, and wind conditions during takeoff, cruise, and landing phases.",
]

PDF_URL = "https://www.faa.gov/sites/faa.gov/files/regulations_policies/handbooks_manuals/aviation/airplane_handbook/00_afh_full.pdf"
